### ISSUE TITLE
Group parameter not passed as argument to closure/anon. fct.

### ISSUE THREAD

**Issue by awagner-mainz** [digicademy/open-sphinxsearch#1]
Error message:

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function Digicademy\OpenSphinxSearch\{closure}(), 0 passed and exactly 1 expected in /opt/opensphinxsearch/public/index.php:457 Stack trace: #0 [internal function]: Digicademy\OpenSphinxSearch\{closure}() #1 /opt/opensphinxsearch/vendor/slim/slim/Slim/Slim.php(551): call_user_func(Object(Closure)) #2 /opt/opensphinxsearch/public/index.php(662): Slim\Slim->group('/:index', Object(Closure)) #3 {main} thrown in /opt/opensphinxsearch/public/index.php on line 457

Changing the following in line 457 fixes it, at least it does in my system:
```
-$app->group('/:index', function ($index) use ($app) {
+$app->group('/:index', function () use ($app) {
```

Versions:
Ubuntu 16.04LTS
````
> apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-07-27T14:34:01
````
````
> php-fpm7.1 --version
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi) (built: Jul  7 2017 09:41:45)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
````
````
> composer -V
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34
````

git commit 5a12380.

**Comment by awagner-mainz** [comment]
(As a sidenote: oss has been installed via ansible role, the files of which are in the project's/serveradmin svn.)

**Comment by metacontext** [comment]
Interestingly I was not able to reproduce this bug in my Debian based setup. But since the Slim docs allow the definition of group closures without route parameters it is safe to skip the parameter  (http://docs.slimframework.com/routing/groups/).
